# Ramdisk
PRODUCT_PACKAGES += \
    init.class_main.sh \
    init.crda.sh \
    init.mdm.sh \
    init.nubia.cpreclog.sh \
    init.qcom.class_core.sh \
    init.qcom.coex.sh \
    init.qcom.crashdata.sh \
    init.qcom.debug.sh \
    init.qcom.early_boot.sh \
    init.qcom.efs.sync.sh \
    init.qcom.post_boot.sh \
    init.qcom.sdio.sh \
    init.qcom.sensors.sh \
    init.qcom.sh \
    init.qcom.syspart_fixup.sh \
    init.qcom.usb.sh \
    init.qcom.wifi.sh \
    init.qti.fm.sh \
    init.qti.ims.sh \
    init.qti.qseecomd.sh \
    qca6234-service.sh \
    init.dmapp.rc \
    init.msm.usb.configfs.rc \
    init.nb.core.rc \
    init.nb.exfat.rc \
    init.nb.nfc.rc \
    init.nb.rc \
    init.nb.systrace.rc \
    init.nubia.Light.rc \
    init.nubia.fingerprint.rc \
    init.nubia.mmi.rc \
    init.nubia.platform.rc \
    init.nubia.sensors.rc \
    init.nubia.touch.rc \
    init.nubia.usb.rc \
    init.project.rc \
    init.qcom.factory.rc \
    init.qcom.rc \
    init.qcom.usb.rc \
    init.target.rc \
    fstab.qcom \
    ueventd.qcom.rc \
