PRODUCT_PROPERTY_OVERRIDES += \
    persist.dbg.volte_avail_ovr=0 \
    persist.dbg.vt_avail_ovr=0 \
    persist.dbg.wfc_avail_ovr=0 \
    persist.vendor.radio.voice_on_lte=1 \
    ro.bluetooth.emb_wp_mode=false \
    ro.bluetooth.wipower=false \
    debug.sf.nobootanimation=0 \
    ro.sf.lcd_density=440 \
    vendor.display.enable_default_color_mode=true \
    import \
    /system/hydrogen_generic.prop \
    persist.dbg.allow_ims_off=0 \
    persist.sys.cmas.pst.eta=false \
    persist.sys.cmas.pst.rmt=false \
    ro.cm.operator=VZW \
    vzw.service.entitlement=true \
    persist.vendor.radio.lte_vrte_ltd=1 \
    ril.subscription.types=RUIM \
    ro.com.android.dataroaming=true \
    ro.telephony.default_network=9 \
    persist.sys.ssr.restart_level=ALL_DISABLE \
